### ISSUE TITLE
we need a findhit/strider-docker-findhit based image with mysql preconfigured

### ISSUE THREAD

**Issue by cusspvz** [findhit/auto-advanced-search#12]
@fernadoneto could you please provide a docker image based on top of `findhit/strider-docker-findhit` with mysql server and client resources installed?

Tests aren't running because we need mysql on test environment - http://strider.findhit.com/findhit/auto-advanced-search/

**Comment by fernandoneto** [comment]
deal

**Comment by fernandoneto** [comment]
@cusspvz you can found image [here](https://github.com/fernandoneto/strider-docker-aas).

fell free to close this issue

**Comment by cusspvz** [comment]
Seems that [strider](http://strider.findhit.com/findhit/auto-advanced-search/) is finally running test units. Thanks @fernandoneto . Closing this up
