### ISSUE TITLE
String invalidated must be returned as it is.

### ISSUE THREAD

**Issue by brunocasanova** [findhit/auto-advanced-search#3]
If the String is invalidated, it returns `''` an empty String, but this doesn't seems to work if i searched by a number, it just kills my query instead breaking throw as clean number.

Ex. https://github.com/findhit/auto-advanced-search/blob/master/lib/query.js#L10

**Comment by cusspvz** [comment]
You have to place the type evaluation as first condition, otherwise you won't have `.length` property.
